#  Taps
tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "sambadevi/powerlevel9k"

# Brews (Packages)
brew "git"
brew "bat"
brew "exa"
brew "python@3.9"
brew "httpie"
brew "newman"
brew "prettier"
brew "sbt"
brew "yarn"
brew "eth-p/software/bat-extras"
brew "sambadevi/powerlevel9k/powerlevel9k"

# Casks (Applications)
cask "macdown"
cask "alfred"
cask "dropbox"
cask "google-chrome"
cask "visual-studio-chrome"
cask "jetbrains-toolbox"
cask "brave-browser"
cask "dissenter-browser"
cask "gitkraken"
cask "slack"
